/// <summary>
/// Team has been working on this as a whole by adding codes as they come up.
/// </summary>
namespace TheWritersCompanion
{
    /// <summary>
    /// Descriptive codes used for error handling.
    /// </summary>
    public enum OutcomeCode
    {
        // GENERIC
        SUCCESS,
        FAILURE,

        // NOTE
        NOTE_ALREADY_EXISTS,
        NOTE_DOES_NOT_EXIST,
        INVALID_NOTE_NAME,
        UNABLE_TO_CREATE_NOTE,
        UNABLE_TO_SAVE_NOTE,
        UNABLE_TO_DELETE_NOTE,
        NOTE_NOT_SELECTED,
        
        // CATEGORY
        CATEGORY_ALREADY_EXISTS,
        CATEGORY_DOES_NOT_EXIST,
        INVALID_CATEGORY_NAME,
        UNABLE_TO_CREATE_CATEGORY,
        UNABLE_TO_SAVE_CATEGORY,
        UNABLE_TO_DELETE_CATEGORY,
        CATEGORY_NOT_SELECTED,

        // REMOTE STORAGE
        INAVLID_USER_CREDENTIALS,
        UNABLE_TO_CONNECT_TO_DATABASE,
        UNABLE_TO_SYNC_DATABASE,
        UNABLE_TO_INSERT_ROW_INTO_DATABASE,
        PROJECT_DOES_NOT_EXIST_IN_DATABASE,
        UNABLE_TO_RETRIEVE_CATEGORIES,
        UNABLE_TO_RETRIEVE_NOTES,
        UNABLE_TO_INSERT_NOTE_INTO_DATABASE,
        UNABLE_TO_INSERT_CATEGORY_INTO_DATABASE,
        UNABLE_TO_INSERT_PROJECT_INTO_DATABASE,

        // DIRECTORY
        INVALID_FILE_ENTRY,
        DIRECTORY_PATH_EMPTY_OR_INVALID_CHARACTERS,
        DIRECTORY_PATH_INVALID_PERMISSIONS,
        DIRECTORY_PATH_TOO_LONG,
        DIRECTORY_PATH_UNSPECIFIED_ERROR,
        DIRECTORY_NOT_EMPTY,
        DIRECTORY_DOES_NOT_EXIST,

        // PROJECT EXISTENCE CONFLICT
        PROJECT_DOES_NOT_EXIST,
        PROJECT_ALREADY_EXISTS,
        UNABLE_TO_CREATE_PROJECT_ROOT_FOLDER,

        // CONFIG FILE
        UNABLE_TO_CREATE_PROJECT_CONFIG_FILE,

        // UI FORMATTING ERRORS
        MULTIPLE_FONTS_SELECTED,
        ZOOM_FACTOR_OUT_OF_RANGE,
        ZOOM_FACTOR_MALFORMATTED
    }
}
